
const CONTACTS_FETCH_BEGIN = 'CONTACTS_FETCH_BEGIN';
const CONTACTS_FETCH_SUCCESS = 'CONTACTS_FETCH_SUCCESS';
const CONTACTS_FETCH_FAILURE = 'CONTACTS_FETCH_FAILURE';
const CONTACT_DETAILS_FETCH_BEGIN = 'CONTACT_DETAILS_FETCH_BEGIN';
const CONTACT_DETAILS_FETCH_SUCCESS = 'CONTACT_DETAILS_FETCH_SUCCESS';
const CONTACT_DETAILS_FETCH_FAILURE = 'CONTACT_DETAILS_FETCH_FAILURE';
const CONTACT_DETAILS_SAVE_BEGIN = 'CONTACT_DETAILS_SAVE_BEGIN';
const CONTACT_DETAILS_SAVE_SUCCESS = 'CONTACT_DETAILS_SAVE_SUCCESS';
const CONTACT_DETAILS_SAVE_FAILURE = 'CONTACT_DETAILS_SAVE_FAILURE';
const CONTACT_DETAILS_DELETE_BEGIN = 'CONTACT_DETAILS_DELETE_BEGIN';
const CONTACT_DETAILS_DELETE_SUCCESS = 'CONTACT_DETAILS_DELETE_SUCCESS';
const CONTACT_DETAILS_DELETE_FAILURE = 'CONTACT_DETAILS_DELETE_FAILURE';
const REQUEST_EDIT_CONTACT = 'REQUEST_EDIT_CONTACT';
const REQUEST_NEW_CONTACT = 'REQUEST_NEW_CONTACT';
const EDIT_CONTACT_CONTACT_CHANGED = 'EDIT_CONTACT_CONTACT_CHANGED';
const DELETE_CONTACT_BEGIN = 'DELETE_CONTACT_BEGIN';
const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';
const SAVE_CONTACT_BEGIN = 'SAVE_CONTACT_BEGIN';
const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS';
const SAVE_CONTACT_FAILURE = 'SAVE_CONTACT_FAILURE';

export const CONTACT_ACTION_TYPE = Object.freeze({
    CONTACTS_FETCH_BEGIN,
    CONTACTS_FETCH_SUCCESS,
    CONTACTS_FETCH_FAILURE,
    CONTACT_DETAILS_FETCH_BEGIN,
    CONTACT_DETAILS_FETCH_SUCCESS,
    CONTACT_DETAILS_FETCH_FAILURE,
    CONTACT_DETAILS_SAVE_BEGIN,
    CONTACT_DETAILS_SAVE_SUCCESS,
    CONTACT_DETAILS_SAVE_FAILURE,
    CONTACT_DETAILS_DELETE_BEGIN,
    CONTACT_DETAILS_DELETE_SUCCESS,
    CONTACT_DETAILS_DELETE_FAILURE,
    REQUEST_EDIT_CONTACT,
    REQUEST_NEW_CONTACT,
    EDIT_CONTACT_CONTACT_CHANGED,
    DELETE_CONTACT_BEGIN,
    DELETE_CONTACT_SUCCESS,
    DELETE_CONTACT_FAILURE,
    SAVE_CONTACT_BEGIN,
    SAVE_CONTACT_SUCCESS,
    SAVE_CONTACT_FAILURE
});